title: <p align="center"> Siti Aini </p>
logo: "/images/logo.png?raw=true" 
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/siti-aini/">LinkedIn</a> |
  <a href="https://github.com/sitiaini13">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursuing a bachelor's degree in mathematics at the Universitas Pendidikan Indonesia.
  <br><br>
  I am currently an independent study participant at Zenius with a focus on data analytics.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
